---
title: "Evaluación del curso de Spark"
author: "Carlos J. Gil Bellosta"
date: "2017-06-22"
output: html_document
---

## Instrucciones generales

Para la evaluación del curso, necesito que me enviéis la versión html o pdf de la salida de este Rmd (obviamente, modificado con las respuestas a los ejercicios) antes del miércoles 28 de junio de 2017 a la dirección de correo electrónico `gilbellosta@gmail.com`. Usad el asunto: **Evaluación curso Spark UPC 2017** para evitar que se me traspapele.

Hay tres ejercicios, cada uno de los cuales estará calificado con 3 puntos. El punto final, hasta diez, me lo reservo para calificar subjetivamente la calidad del código y/o gráficos: que sea breve, esté bien indentado, que tengan (los gráficos) una mínima gracia, que los ejes estén convenientemente etiquetados, etc.

Los ejercicios tienen pistas y/o instrucciones. Leedlas bien.

## Ejercicios

### Ejercicio 1: análisis de la EPA

El INE publica los microdatos de la EPA (encuesta de población activa) [aquí](http://www.ine.es/prodyser/microdatos.htm). El objetivo es utilizar Spark para replicar los cálculos realizados por el INE para la publicación de los últimos resultados (1T de 2017). Las cifras publicadas por el INE fueron (véase la [nota de prensa](http://www.ine.es/daco/daco42/daco4211/epa0117.pdf)): 

1. Número de parados, 4255000.
2. Tasa de paro, 18.75%.

**Nota:** Los anteriores son números aproximados; los resultados que obtengas, no obstante, tienen que ser, _prácticamente_ iguales.

Para realizar los cálculos:

1. Descarga, descomprime, etc. el fichero de microdatos correspondiente al trimestre 2017T1 de la EPA. Exáminalo, si quieres, con un editor de texto decente.
2. Usa el paquete `MicroDatosEs` de R para leer el fichero e importarlo como un `data.frame` de R. **Nota:** Si usas Windows, puede que falle la versión del paquete que está en CRAN. En tal caso, prueba a instalar la versión de MicroDatosEs de GitHub. Igual tienes que investigar cómo instalar paquetes directamente desde GitHub.
3. Sube la tabla a Spark desde R.
4. Realiza la agregación pertinente en Spark. Pero ten en cuenta lo siguiente:

    1. La situación laboral de los sujetos está dada por la columna AOI de la tabla.
    2. La tasa de paro es el cociente entre los parados y los activos. Ten en cuenta de que la columna AOI tiene varios tipos de parados y que la población activa está compuesta por los parados y los ocupados (o todos menos los inactivos y los que tienen la columna AOI nula (es decir, los niños)).
    3. Para sumar personas, en la EPA (y otras encuestas) no se cuentan filas sino que se suma la columna FACTOREL. Esta columna indica a cuántas personas _representa_ el encuestado en cuestión de acuerdo con los criterios de muestreo del INE. Ten en cuenta además que FACTOREL hay que dividirlo por 100. Si sumas FACTOREL y divides por 100, obtienes un valor de alrededor de 46 millones, que es la población española total.
    

### Ejercicio 2: EPA por provincias

Repite el ejercicio anterior, pero esta vez agregando por provincias; es decir, produce una tabla en la que apareca la provincia, su tasa de paro y el número de parados. Ordénala por tasa de paro descendente.

### Ejercicio 3: Ejercicio libre

Usando la tabla anterior, haz un análisis adicional y descríbelo en 2 o 3 párrafos, con o sin gráficos. En las páginas del INE se listan las columnas y su significado, si es que tienes dudas. Usa, por supuesto, Spark para las agregaciones y las manipulaciones de datos, aunque puedes usar R para los gráficos, si procede.